server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:8081/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
        ddl-auto: create-drop
    show-sql: false


indexing-settings:
  siteConfigs:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://nikoartgallery.com
      name: nikoartgallery
#    - url: https://lenta.ru
#      name: lenta.ru


jsoup-connection-properties:
  userAgent: "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referer: "http://www.google.com"


wrong-types: pdf,jpeg,jpg,xml,png