version: '3'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=search_engine
    ports:
      - '8081:3306'


  search-engine:
    container_name: search-engine
    build: '.'
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    ports:
      - "8080:8080"
    restart: on-failure
